repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args:
        - --line-length=140
        - --preview
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: ['--manifest-path', 'gui/src-tauri/Cargo.toml', '--']
    -   id: cargo-check
        args: ['--manifest-path', 'gui/src-tauri/Cargo.toml']
    -   id: clippy
        args: ['--manifest-path', 'gui/src-tauri/Cargo.toml']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
    -   id: clang-format
        exclude: ^external/
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
    -   id: prettier
        types_or: [css, javascript, svelte]
        additional_dependencies:
        -   prettier@2.7.0
        -   'prettier-plugin-svelte@2.10.0'